import { Link } from "react-router-dom";
import { ProjectImportDropzone } from "../components/portfolio/import/ProjectImportDropzone";
import { ProjectImportMappings } from "../components/portfolio/import/ProjectImportMappings";
import { ProjectImportOptions } from "../components/portfolio/import/ProjectImportOptions";
import { ProjectImportPreview } from "../components/portfolio/import/ProjectImportPreview";
import { ProjectImportProgress } from "../components/portfolio/import/ProjectImportProgress";
import { ProjectImportResults } from "../components/portfolio/import/ProjectImportResults";
import { ProjectImportSummary } from "../components/portfolio/import/ProjectImportSummary";
import { ProjectImportTypeStep } from "../components/portfolio/import/ProjectImportTypeStep";
import { PageHeading } from "../components/shared/PageHeading";
import { AdminIcon } from "../components/shared/AdminIcon";
import { useProjectImport } from "../hooks/useProjectImport";

export function PortfolioImportPage() {
  const importer = useProjectImport();
  const step = importer.results ? 4 : importer.validation ? 3 : importer.rows.length ? 2 : 1;
  return <><PageHeading title="Import Portfolio CSV" description="Bulk import portfolio projects from a CSV file. Validate and preview your data before importing."><Link className="button button-secondary" to="/portfolio">Back to Portfolio</Link></PageHeading><ProjectImportProgress step={step} /><div className="import-layout"><ProjectImportTypeStep value={importer.projectType} configs={importer.projectTypes} onChange={importer.setProjectType} /><ProjectImportDropzone config={importer.config} file={importer.file} busy={importer.busy} rowCount={importer.rows.length} onFile={importer.parseFile} onDownload={importer.downloadTemplate} onRemove={importer.reset} /><ProjectImportOptions duplicateStrategy={importer.duplicateStrategy} emptyCellStrategy={importer.emptyCellStrategy} statusStrategy={importer.statusStrategy} createMissingCategories={importer.createMissingCategories} onDuplicateStrategy={importer.setDuplicateStrategy} onEmptyCellStrategy={importer.setEmptyCellStrategy} onStatusStrategy={importer.setStatusStrategy} onCreateMissingCategories={importer.setCreateMissingCategories} /></div><div aria-live="polite">{importer.busy ? <p className="notice">Working...</p> : null}{importer.error ? <p className="notice error">{importer.error}</p> : null}{importer.parseWarnings.map((warning) => <p className="notice" key={warning}>{warning}</p>)}</div><article className="panel import-safety"><AdminIcon name="check" /><div><h2>Your data is safe</h2><p>Nothing is imported until validation and confirmation. You can review every row before importing.</p></div><button className="button button-primary" type="button" disabled={importer.busy || !importer.projectType || importer.rows.length === 0 || Boolean(importer.results)} onClick={importer.validate}>{importer.busy ? "Validating..." : "Validate & Preview"}</button></article>{importer.validation ? <><ProjectImportSummary summary={importer.validation.summary} /><ProjectImportMappings rows={importer.validation.rows} technologies={importer.technologies} categories={importer.categories} technologyMappings={importer.technologyMappings} categoryMappings={importer.categoryMappings} createMissingCategories={importer.createMissingCategories} onTechnologyMapping={importer.setTechnologyMapping} onCategoryMapping={importer.setCategoryMapping} onRevalidate={importer.validate} /><ProjectImportPreview rows={importer.validation.rows} selectedRows={importer.selectedRows} busy={importer.busy} onToggle={importer.toggleRow} onCommit={importer.commit} /></> : null}{importer.results ? <ProjectImportResults results={importer.results} onReset={importer.reset} /> : null}</>;
}
